config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { registrations: 'usuarios/registrations' }
  
  get 'principal/index'
  
  get 'principal/registrado'
  post 'principal/download_pdf'
  post 'principal/autorizar'

  post 'principal/asociar'
  post 'principal/movimientos'
  post 'principal/cuentas'

  post 'principal/cambiar'
  post 'principal/duda'

  post 'principal/cargarmovimientos'

  patch 'principal/movimientoupdate'

  delete 'principal/movimientoborrar'

  patch 'principal/movimientofin'

  post 'principal/download_factura'
  patch 'principal/download_factura'


  get 'principal/eventos'
  patch 'principal/eventos_registrar'
  post 'principal/eventos_registrar'
  get 'principal/eventos_registrado'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'principal/registro'
  patch 'principal/validarregistro'
  patch 'principal/enviarpassword'

  patch 'principal/inscribir'
  post 'principal/download_inscripcion'
  patch 'principal/download_inscripcion'
  post 'principal/download_ayuda'
  patch 'principal/download_ayuda'

  root 'principal#index'
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController

  $movimientosnuevos

  def eventos
    @evento_usuario = EventoUsuario.new()
  end

  def eventos_registrar

    evento_usuario = EventoUsuario.new(
          nombres: params[:evento_usuario][:nombres], 
          apellidos: params[:evento_usuario][:apellidos], 
          telefono: params[:evento_usuario][:telefono], 
          celular: params[:evento_usuario][:celular], 
          direccion: params[:evento_usuario][:direccion], 
          nacimiento: params[:evento_usuario][:nacimiento], 
          nacionalidad: params[:evento_usuario][:nacionalidad],
          email: params[:evento_usuario][:email], 
          horarios: params[:evento_usuario][:horarios], 
          universidad_completa: params[:evento_usuario][:universidad_completa], 
          universidad_incompleta: params[:evento_usuario][:universidad_incompleta], 
          trabajo: params[:evento_usuario][:trabajo], 
          ultimo_trabajo: params[:evento_usuario][:ultimo_trabajo], 
          comentarios: params[:evento_usuario][:comentarios] 
          )
    evento_usuario.save!

    UserMailer.eventos_usuario(evento_usuario).deliver_now

    redirect_to principal_eventos_registrado_path
  end

  def eventos_registrado

  end

  def index



    @x = Actividad.new()
    @y = ActividadAlumno.new()
    @usuario = Usuario.new()
    @actividad = ActividadAlumno.new()

    @cuenta = Cuenta.new()

    if usuario_signed_in?

      usuario = current_usuario.id 
      @alumnos = Alumno.where([
        "id IN (SELECT cuenta_alumnos.alumno_id FROM ( cuentas INNER JOIN titular_cuentas ON cuentas.id=titular_cuentas.cuenta_id ) INNER JOIN cuenta_alumnos ON cuentas.id=cuenta_alumnos.cuenta_id WHERE titular_cuentas.usuario_id=?)" +
        " OR " +
        "id IN (SELECT padre_alumnos.alumno_id FROM padre_alumnos WHERE padre_alumnos.usuario_id=?)",
        usuario, usuario]).order(:nombre)

      @cuentas = Cuenta.where(["id IN (SELECT cuenta_id FROM titular_cuentas WHERE usuario_id = ?)", usuario])
      #@cuentas = Cuenta.where("id IN (SELECT DISTINCT cuenta FROM usuarios)").order(:id)
      #@cuentas = Cuenta.where(["id = ?",12338])

      #File.open(Rails.root.join("data", 'movimientos.txt'),'w') do |f|          
        @movimientos = Array.new
        @cuentas.each do |cuenta|
          movs = Movimiento.where(["cuenta_id = ? AND not pendiente", cuenta.id]).order(:fecha,:tipo,:alumno,:descripcion)
          @movimientos.push( [cuenta.id, movs ] )
    
          # saldo = 0
          # movs.each do |m|
          #   saldo = saldo + m.debe - m.haber
          #   f.puts m.cuenta_id.to_s + ";" + m.alumno.to_s + ";" + m.fecha.to_s + ";" + m.descripcion + ";" + m.extra + ";" + m.debe.to_s + ";" + m.haber.to_s + ";" + saldo.to_s
          # end
          #f.puts ""
        end
      #end

        if current_usuario.cedula == 16 
          @noregistrado = Alumno.where("id NOT IN (SELECT cuenta_alumnos.alumno_id FROM cuenta_alumnos INNER JOIN titular_cuentas ON cuenta_alumnos.cuenta_id=titular_cuentas.cuenta_id) AND id IN (SELECT alumno_id FROM actividad_alumnos)").order(:nombre)
          @van = Alumno.where("id IN (SELECT cuenta_alumnos.alumno_id FROM cuenta_alumnos INNER JOIN titular_cuentas ON cuenta_alumnos.cuenta_id=titular_cuentas.cuenta_id) AND id IN (SELECT alumno_id FROM actividad_alumnos WHERE opcion=1 OR opcion=2)").order(:nombre)
          @novan = Alumno.where("id IN (SELECT cuenta_alumnos.alumno_id FROM cuenta_alumnos INNER JOIN titular_cuentas ON cuenta_alumnos.cuenta_id=titular_cuentas.cuenta_id) AND id IN (SELECT alumno_id FROM actividad_alumnos WHERE opcion=0)").order(:nombre)
          @noeligio = Alumno.where("id IN (SELECT cuenta_alumnos.alumno_id FROM cuenta_alumnos INNER JOIN titular_cuentas ON cuenta_alumnos.cuenta_id=titular_cuentas.cuenta_id) AND id IN (SELECT alumno_id FROM actividad_alumnos WHERE opcion IS NULL)").order(:nombre)
        elsif current_usuario.cedula == 19873943  
          @van = Alumno.where("id IN (SELECT cuenta_alumnos.alumno_id FROM cuenta_alumnos INNER JOIN titular_cuentas ON cuenta_alumnos.cuenta_id=titular_cuentas.cuenta_id) AND id IN (SELECT alumno_id FROM actividad_alumnos WHERE actividad_id=3 AND opcion=1)").order(:nombre)
        end
    else
      @alumnos = nil
    end
  end

  def download_pdf

    p params[:actividad][:id]


    actividad = Actividad.find(params[:actividad][:id])
    if ( actividad != nil )
      file_name = "#{actividad.nombre}.pdf"
      file = Tempfile.new(file_name)
      

      pdf = CombinePDF.new
      ActividadArchivo.where("actividad_id=#{params[:actividad][:id]}").order(:id).each do |arch|
        
        file2_name = "#{arch.nombre}"
        file2 = Tempfile.new(file2_name)
        IO.binwrite(file2.path, arch.data)
        pdf << CombinePDF.load(file2.path)

      end
      pdf.save file.path

      actividad_alumno = ActividadAlumno.find_by(actividad_id: params[:actividad][:id], alumno_id: params[:actividad][:alumno_id])
      actividad_alumno.update!( bajado: DateTime.now)

      send_file(
        file.path,
        filename: file_name,
        type: "application/pdf"
      )

    # actividad = Actividad.find(params[:actividad][:id])    
    # if ( actividad != nil )
    #   file = Tempfile.new("actividad.pdf")
    #   IO.binwrite(file.path, actividad.data)

    #   send_file(
    #     file.path,
    #     filename: actividad.archivo,
    #     type: "application/pdf"
    #   )

    else
      redirect_to root_path
    end
  end

  def autorizar
    p ""
    p params[:actividad_alumno][:alumno_id]
    p params[:actividad_alumno][:opcion]
    p ""
    p ""    

    actividad_alumno = ActividadAlumno.where( ["alumno_id = ? AND actividad_id = ?", params[:actividad_alumno][:alumno_id], params[:actividad_alumno][:actividad_id]]).first rescue nil

    if ( actividad_alumno != nil )

      actividad_alumno.elegir_opcion(params[:actividad_alumno][:opcion])

      actividad_alumno.opcion = params[:actividad_alumno][:opcion]
      actividad_alumno.fecha = params[:actividad_alumno][:fecha]
      actividad_alumno.save!()

    end
    redirect_to root_path
  end

  require 'digest/md5'
  
  def digito(cedula)
    if ( cedula == nil )      
      return false
    end
    suma = 0
    arr = [4,3,6,7,8,9,2]
    digit = cedula%10 
    c = cedula/10
    (0..6).each do |i|
       r = c%10
       c = c/10
       suma = (suma + r*arr[i]) % 10
    end
    return (digit == ((10-(suma%10))%10))
  end

  def asociar
    if ( !digito(params[:usuario][:cedula].to_i) )
      p "Error en cedula"
      return
    end

    @usuario = Usuario.where( ["cedula = ?", params[:usuario][:cedula]]).first rescue nil
    if ( @usuario != nil )
      password =  Digest::MD5.hexdigest(params[:usuario][:cedula] + DateTime.now.strftime('%Y%m%d%H%M%S'))[0..7]
      p password
      @usuario.update( password: password, password_confirmation: password );
      # if ( params[:usuario][:alumno2] == "1")
      #   TitularCuenta.create(usuario_id: @usuario.id, cuenta_id: params[:usuario][:alumno1].to_i)
      # else
      #   CuentaAlumno.where( ["cuenta_id = ?", params[:usuario][:alumno1].to_i ]).each do |e|
      #     PadreAlumno.create(usuario_id: @usuario.id, alumno_id: e.alumno_id )
      #   end
      # end
    end        
    redirect_to root_path
  end

  def cambiar
    #cuentas = Cuenta.where("id IN (SELECT DISTINCT cuenta_id FROM movimientos WHERE NOT valido AND NOT duda AND descripcion LIKE 'Cuota %')")

    # cuentas = Cuenta.all
    # cuentas.each do |cuenta|
    #   (1..5).each do |alumno|
    #     movs = Movimiento.where(["cuenta_id = ? AND alumno = ? AND descripcion LIKE 'Cuota%/%'", cuenta.id, alumno]).order(:fecha)
    #     c = 1
    #     movs.each do |mov|
    #       mov.descripcion = 'Cuota ' + c.to_s + '/' + movs.count.to_s
    #       mov.save!
    #       c = c + 1
    #     end

    #     movs = Movimiento.where(["cuenta_id = ? AND alumno = ? AND descripcion LIKE 'Descuento%/%'", cuenta.id, alumno]).order(:fecha)
    #     c = 1
    #     movs.each do |mov|
    #       mov.descripcion = 'Descuento ' + c.to_s + '/' + movs.count.to_s
    #       mov.save!
    #       c = c + 1
    #     end
    #   end
    # end

    # (1..12).each do |mes|
    #   p mes

    #   m = Movimiento.new()
    #   m.cuenta_id = 13917
    #   m.alumno = 1
    #   m.fecha = DateTime.new(2018,mes,1,0,0,0)
    #   m.descripcion = 'Cuota ' + mes.to_s + "/12"
    #   m.extra = 0
    #   m.debe = 9200
    #   m.haber = 0
    #   m.tipo = 2 
    #   m.pendiente = ( m.fecha < DateTime.new(2018,6,1,0,0,0) )
    #   m.valido = false    
    #   m.duda = false
    #   m.save!

    #   m = Movimiento.new()
    #   m.cuenta_id = 13917
    #   m.alumno = 1
    #   m.fecha = DateTime.new(2018,mes,1,0,0,0)
    #   m.descripcion = 'Descuento ' + mes.to_s + "/12"
    #   m.extra = 0
    #   if ( m.fecha < DateTime.new(2018,6,1,0,0,0) )
    #     m.debe = -9200
    #   else
    #     m.debe = -272
    #   end
    #   m.haber = 0
    #   m.tipo = 3 
    #   m.pendiente = ( m.fecha < DateTime.new(2018,6,1,0,0,0) )
    #   m.valido = false    
    #   m.duda = false
    #   m.save!
    # end

    # (225..235).each do |num|
    #   usuario = Usuario.find(num)
    #   if ( usuario != nil  && usuario.validado && ( usuario.mail == nil || !usuario.mail ) )
    #     p usuario.passwd

    #     usuario.mail = true
    #     usuario.save

    #     usuario.update( password: usuario.passwd, password_confirmation: usuario.passwd );
    #     if ( usuario.titular )
    #       TitularCuenta.create(usuario_id: usuario.id, cuenta_id: usuario.cuenta)
    #     else
    #       CuentaAlumno.where( ["cuenta_id = ?", usuario.cuenta ]).each do |e|
    #         PadreAlumno.create(usuario_id: usuario.id, alumno_id: e.alumno_id )
    #       end
    #     end
    #     UserMailer.aceptar_usuario(usuario).deliver_now
    #   end 
    # end     
    redirect_to root_path
  end


  def duda

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/principal/_actividades.html.erb
<% t = locals[:alumno] %>
<% @act = ActividadAlumno.where(['alumno_id = ?',t.id]).order("actividad_id") %>
<% if (@act != nil) %>
	<% @act.each do |a| %>
		<% @actividad = Actividad.find(a.actividad_id) rescue nil %>
		<% if @actividad != nil && (@actividad.fecha == nil || @actividad.fecha >= DateTime.now ) %>
		    <br>
			
			<%= form_for(@x, as: :actividad, url: principal_download_pdf_path(:actividad), :html => {:id=>'form_download_' + a.actividad_id.to_s}) do |f| %>
	           <%= f.hidden_field :id, value: @actividad.id %>
	           <%= f.hidden_field :alumno_id, value: t.id %>
			    <div id="textoRegistrarse">
					<b><%= link_to "Descargar información: " + @actividad.nombre, "", :onclick => "$('#form_download_" + a.actividad_id.to_s + "').submit()" %></b>
			    </div>
			<% end %>

		    <% @cuenta = CuentaAlumno.where(['alumno_id = ?',t.id]).first rescue nil %>
		    <% @titular = TitularCuenta.where(['usuario_id = ? AND cuenta_id = ?',current_usuario.id,@cuenta.cuenta_id]).first rescue nil %>
		    <% arreglo = ActividadOpcion.opciones(@actividad.id,false) %>
		    <% arregloTodo = ActividadOpcion.opciones(@actividad.id,true) %>
		    <% if @titular != nil && arreglo[:opciones].count > 0 %>
				<%= form_for(@y, as: :actividad_alumno, url: principal_autorizar_path(:actividad)) do |f| %>
					<div id="textoRegistrarse">	
				    <% if a.opcion != nil && arregloTodo[:elecciones][a.opcion] != nil %>
				    	<b><%= p arregloTodo[:elecciones][a.opcion] %></b>
				    <% else %>
				    	<b><%= p "" %></b>
				    <% end %><br><br>
		            <%= f.hidden_field :alumno_id, value: t.id %>
		            <%= f.hidden_field :actividad_id, value: a.actividad_id %>
		            <%= f.hidden_field :fecha, value: DateTime.now %>
					<%= f.select :opcion, options_for_select(arreglo[:opciones], a.opcion)  %><br><br>
		            <%= f.submit "Confirmar"  %>
					</div>
				<% end %>												
				<br>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/principal/_inscripciones.html.erb
<% if @cuentas.count == 0 %>
  <table>
    <tr height='30px'></tr>
    <tr height='30px'><td width='30px'></td><td width='15px'><%= image_tag("warning.png") %></td>
    <td width='30px'></td>
    <td><%= p "Debe ser el titular de la cuenta para realizar la reinscripción" %></td></tr>
    <tr height='30px'></tr>
  </table>
<% else %>
  <% alu = locals[:alumno] %>
  <% inscripcionAlumno = Inscripcion2020.FindInscripcion(alu.id) %>
  <% if inscripcionAlumno == nil || (inscripcionAlumno.inhabilitado == nil) %>
  
  <% elsif !inscripcionAlumno.PuedeInscribir() %>
    <table>
      <tr height='30px'></tr>
      <tr height='30px'><td width='30px'></td><td width='15px'><%= image_tag("warning.png") %></td>
      <td width='30px'></td>
      <td><%= p "Reinscripción Inhabilitada. Comuníquese con administración" %></td></tr>
      <tr height='30px'></tr>
    </table>
  <% elsif inscripcionAlumno.EstaInscripto() %>
    <div class="col-md-12 col-sm-12 col-xs-12 content-table">
      <table>
        <tr height='30px'></tr>
        <tr height='30px'><td width='30px'></td><td width='15px'><%= image_tag("tick.png") %></td>
        <td width='30px'></td>
        <td><%= p "El alumno está inscripto" %></td></tr>
        <tr height='30px'></tr>
      </table>
    </div>
    <div class="clearfix"></div>
  <% elsif inscripcionAlumno.HayVale() %>
    <%= form_for(inscripcionAlumno, as: :inscripcionAlumno, url: principal_download_inscripcion_path(:inscripcionAlumno), :html => {:id=>'form_download_inscripcion_' + inscripcionAlumno.alumno_id.to_s}) do |f| %>
      <%= f.hidden_field :alumno_id, value: inscripcionAlumno.alumno_id %>
      <div id="textoRegistrarse">
        <b><%= link_to "Descargar reinscripción", "", :onclick => "$('#form_download_inscripcion_" + inscripcionAlumno.alumno_id.to_s + "').submit()" %></b>
      </div>
    <% end %>    
  <% elsif inscripcionAlumno.EstaRegistrado() %>
    <div class="col-md-12 col-sm-12 col-xs-12 content-table">
      <table>
        <tr height='30px'></tr>
        <tr height='30px'><td width='30px'></td><td width='15px'><%= image_tag("wait.png") %></td>
        <td width='30px'></td>
        <td><%= p "Se está procesando la información" %></td></tr>
        <tr height='30px'></tr>
      </table>
    </div>
    <div class="clearfix"></div>
  <% else %>    
    <%= form_for(inscripcionAlumno, as: :inscripcionAlumno, url: principal_inscribir_path(:inscripcionAlumno)) do |f| %>
      <div class="col-md-12 col-sm-12 col-xs-12 content-table">
        <div class="panel-body">
          <%= f.hidden_field :alumno_id, value: inscripcionAlumno.alumno_id %>

          <div class="form-group">
            <% opciones = Inscripcion2020.OpcionesGrados(inscripcionAlumno) %>
            <%= f.label "Nivel" %>
            <%= f.select :proximo_grado_id, options_for_select(opciones, inscripcionAlumno.proximo_grado_id), {}, {class: 'form-control'}  %>
          </div>

          <div class="form-group">
            <% opciones = Inscripcion2020.OpcionesConvenio(inscripcionAlumno) %>
            <%= f.label "Convenio: " %>
            <%= f.select :convenio2020_id, options_for_select(opciones, inscripcionAlumno.convenio2020_id), {}, {class: 'form-control'}  %>
          </div>

          <% afinidad = Inscripcion2020.OpcionesAfinidad(inscripcionAlumno) %>
          <% if afinidad != nil && afinidad.descuento != nil %>
            <div class="form-group">
              <%= f.label "Afinidad: " %><br>
              <%= p "#{afinidad.descuento}%" %>
            </div>
          <% end %>

          <% inscripcion = Inscripcion2020.OpcionesAdicional(inscripcionAlumno) %>
          <% if inscripcion != nil && inscripcion.adicional != nil %>
            <div class="form-group">
              <%= f.label "Adicional: " %><br>
              <%= p "#{inscripcion.adicional}%" %>
            </div>
          <% end %>

          <div class="form-group">
            <% opciones = Inscripcion2020.OpcionesHermanos(inscripcionAlumno) %>
            <%= f.label "Hermanos: " %>
            <%= f.select :hermanos2020_id, options_for_select(opciones, inscripcionAlumno.hermanos2020_id), {}, {class: 'form-control'}  %>
          </div>

          <div class="form-group">
            <% opciones = Inscripcion2020.OpcionesCuotas(inscripcionAlumno) %>
            <%= f.label "Cuotas: " %>
            <%= f.select :cuota2020_id, options_for_select(opciones, inscripcionAlumno.cuota2020_id), {}, {class: 'form-control'}  %>
          </div>

          <div class="form-group">
            <% opciones = Inscripcion2020.OpcionesMatricula(inscripcionAlumno) %>
            <%= f.label "Matrícula: " %>
            <%= f.select :matricula2020_id, options_for_select(opciones, inscripcionAlumno.matricula2020_id), {}, {class: 'form-control'}  %>
          </div>

          <%= f.submit "Inscribir", class: 'btn btn-primary', data: { confirm: "A partir de este momento los datos no pueden ser modificados. Está seguro de continuar?" } %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/principal/index.html.erb
<% if usuario_signed_in? && current_usuario.cedula == 19873943 %>

<div class="container">
	<div class="row">
  		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="panel-group">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">
						<a data-toggle="collapse" href="#collapse1"><!--i class="far fa-credit-card"></i--><%= p "Actividad integración campamento 1o Secundaria Montevideo" %></a>
						</h4>
					</div>
<br>
	<div id="collapseu1" class="panel-collapse collapse collapse in">
		<div class="col-md-12 col-sm-12 col-xs-12 content-table">
			<% @van.each do |a| %>
				<%= p a.nombre %><br>
		<% end %><br><br></div>
<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
</div>

<% end %>
<% if usuario_signed_in? && current_usuario.cedula == 16 %>

	<% cuentas = Array.new %>	
	<% Movimiento.where(["not valido and not duda"]).select(:cuenta_id).distinct().order(:cuenta_id).each do |s| %>

		<% cuentas.push( [s.cuenta_id,s.cuenta_id] ) %>
	<% end %>

	<%= form_for(@cuenta, as: :cuenta, url: principal_movimientos_path(:cuenta)) do |f| %>
        <%= f.label "Cuenta (" + cuentas.count.to_s + ") " %>
		<%= f.select :id, options_for_select(cuentas, 0)  %>
		<%= f.submit "Editar" %>
    <% end %>

	<%= form_for(@cuenta, as: :cuenta, url: principal_duda_path(:cuenta)) do |f| %>
        <%= f.label "Cuenta (" + cuentas.count.to_s + ") " %>
		<%= f.select :id, options_for_select(cuentas, 0)  %>
		<%= f.submit "Duda" %>
    <% end %>


	<%= form_for(@cuenta, as: :cuenta, url: principal_cambiar_path(:cuenta)) do |f| %>
        <%= f.label "Cuenta:  " %>
		<%= f.select :id, options_for_select(cuentas, 0)  %>
		<%= f.submit "Cambiar" %>
    <% end %>


	<% cuentasValidas = Array.new %>	
	<% Movimiento.where(["valido"]).select(:cuenta_id).distinct().order(:cuenta_id).each do |s| %>
		<% cuentasValidas.push( [s.cuenta_id,s.cuenta_id] ) %>
	<% end %>

	<%= form_for(@cuenta, as: :cuenta, url: principal_cuentas_path(:cuenta)) do |f| %>
        <%= f.label "Cuenta (" + cuentasValidas.count.to_s + ") " %>
		<%= f.select :id, options_for_select(cuentasValidas, 0)  %>
		<%= f.submit "Ver" %>
    <% end %>

    <%= p $movimientosnuevos %><br><br>

	<%= form_tag({:controller => "principal", :action => "cargarmovimientos"}, :method => "post", :multipart => true) do %>
  		<%= file_field_tag 'archivo', required: "required", multiple: false %>
		<%= submit_tag "Cargar movimientos" %>
	<% end %>

<!--
	<%= p "Cantidad usuarios: " + Usuario.all.count.to_s %><br>
	<%= p "Cantidad cuentas: " + TitularCuenta.all.count.to_s %><br>
	<%= p "Cantidad autorizados: " + ActividadAlumno.where("opcion=1 OR opcion=2").count.to_s %><br>
	<%= p "Cantidad no autorizados: " + ActividadAlumno.where("opcion=0").count.to_s %><br><br>

	<%= form_for(@usuario, as: :usuario, url: principal_asociar_path(:usuario)) do |f| %>
        <div class="form-group">
            <%= f.label "Cedula", style: "font-size: 24px", class: "labelFormulario"  %>
            <%= f.text_field :cedula, autofocus: true, placeholder: "Cedula", style: "font-size: 24px"  %>
        </div>
        <div class="form-group">
            <%= f.label "Cuenta", style: "font-size: 24px", class: "labelFormulario"  %>
            <%= f.text_field :alumno1, autofocus: true, placeholder: "Cuenta", style: "font-size: 24px"  %>
        </div>
        <div class="form-group">
            <%= f.label "Titular", style: "font-size: 24px", class: "labelFormulario"  %>
            <%= f.text_field :alumno2, autofocus: true, placeholder: "Titular", style: "font-size: 24px"  %>
        </div>
        <div id="textoRegistrarse">
        	<%= f.submit "Asociar", style: "font-size: 24px"  %>
        </div>
    <% end %>

	<%= p "Van" %><br>
	<% @van.each do |a| %>
		<%= p a.nombre %><br>
	<% end %><br><br>

	<%= p "No van" %><br>
	<% @novan.each do |a| %>
		<%= p a.nombre %><br>
	<% end %><br><br>

	<%= p "No eligió" %><br>
	<% @noeligio.each do |a| %>
		<%= p a.nombre %><br>
	<% end %><br><br>

	<%= p "No registrados" %><br>
	<% @noregistrado.each do |a| %>
		<%= p a.nombre %><br>
	<% end %>

!>

<% end %>

    

<% if usuario_signed_in? && current_usuario.cedula != 16 && current_usuario.cedula != 19873943 %>

<%= render 'recuadro', locals: { titulo: 'Novedades', form: 'actividades' }  %>

<%= render 'recuadro', locals: { titulo: 'Reinscripción', form: 'inscripciones' }  %>

<%= render 'recuadro_cuenta', locals: { titulo: 'Cuenta corriente', form: 'cuenta_corriente' }  %>

<% end %>


<script>
		$(document).ready(function () {

            $("#tabla tbody tr").each(function (index) {

                var campo1;

                $(this).children("td").each(function (fila) {
                    switch (fila) {
                        case 0:
                            campo1 = $(this).text();
                            break;
                    }
                })

                if (campo1 != "undefined") {

					var texto = campo1 + "";
                	//texto = texto.replace('/-/g', "/");

                	var mes = parseInt(texto.substring(3, 5)); //Obtenemos mes
                	if (mes % 2 == 0) {
                		//alert("Es par");
                		$(this).css("background-color", "#efeded");
                	} else {
                		//alert("Es impar");
                	}
                }
            })

        });

	</script>

app/views/principal/movimientos.html.erb
<% if usuario_signed_in? && current_usuario.cedula == 16 %>

	Movimientos
	<% if @movimientos != nil %>
		<table>
		<% primero = true %>
		<% suma = 0 %>
		<% @movimientos.each do |m| %>
			<tr>
			<%= form_for(m, as: :movimiento, url: principal_movimientoupdate_path(:movimiento)) do |f| %>
				<% if m.tipo >= 0 %>
					<% suma = suma + m.debe - m.haber %>
				<% end %>
				
				<td><%= m.fecha %></td>
				<td><%= f.text_field :alumno %></td>
				<td><%= f.text_field :descripcion %></td>
				<td><%= f.text_field :extra %></td>
				<td><%= f.text_field :tipo %></td>
				<td><%= f.text_field :debe %></td>
				<td><%= f.text_field :haber %></td>
				<td><%= suma %></td>
				<td><%= f.hidden_field :tipo, value: m.tipo %><%= f.hidden_field :id, value: m.id %><%= f.submit "Actualizar" %></td>

			<% end %>
			<%= form_for m, as: :movimiento, url: principal_movimientoborrar_path(:movimiento), method: 'delete' do |f| %>
				<%= f.hidden_field :id, value: m.id %>
				<td><%= f.submit 'Borrar' %></td>
			<% end %>
			<% if primero %>
				<% primero = false %>
				<%= form_for m, as: :movimiento, url: principal_movimientofin_path(:movimiento) do |f| %>
					<%= f.hidden_field :cuenta_id, value: m.cuenta_id %>
					<td><%= f.submit 'Fin' %></td>
				<% end %>
			<% end %>


			</tr>
		<% end %>
		</table>
	<% end %>
<% end %>